-- 1. Tabel untuk menyimpan daftar Saham (Emiten)
-- Contoh: BBCA, TLKM, GOTO
CREATE TABLE public.tickers (
    symbol VARCHAR(10) PRIMARY KEY, -- Primary Key kode saham (misal: BBCA.JK)
    company_name VARCHAR(255) NOT NULL,
    sector VARCHAR(100),
    is_active BOOLEAN DEFAULT true, -- Soft delete flag
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabel Harga Historis (OHLCV)
-- Kita pakai composite primary key (symbol + date) biar gak ada duplikat data harian
CREATE TABLE public.stock_prices (
    symbol VARCHAR(10) REFERENCES public.tickers(symbol) ON DELETE CASCADE,
    date DATE NOT NULL,
    open NUMERIC(15, 2), -- Pakai NUMERIC biar presisi uang tidak meleset
    high NUMERIC(15, 2),
    low NUMERIC(15, 2),
    close NUMERIC(15, 2),
    volume BIGINT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (symbol, date)
);

-- 3. Tabel Hasil Prediksi (Forecasting)
-- Menyimpan hasil ramalan Python
CREATE TABLE public.predictions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol VARCHAR(10) REFERENCES public.tickers(symbol) ON DELETE CASCADE,
    forecast_date DATE NOT NULL, -- Tanggal yang diprediksi
    predicted_price NUMERIC(15, 2) NOT NULL,
    confidence_level VARCHAR(50), -- Misal: 'High', 'Medium' (opsional)
    model_version VARCHAR(50) DEFAULT 'v1-exponential-smoothing', -- Untuk tracking versi algoritma
    created_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Constraint: Satu saham cuma boleh punya 1 prediksi untuk tanggal tertentu dari model yg sama
    UNIQUE (symbol, forecast_date, model_version)
);

-- 4. Tabel Log Error (Untuk Monitoring Enterprise)
-- Biar kalau Python error, kita tau sebabnya tanpa buka server logs
CREATE TABLE public.app_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level VARCHAR(20) NOT NULL, -- INFO, ERROR, WARNING
    message TEXT NOT NULL,
    meta JSONB, -- Simpan data tambahan flexible
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexing (Biar Query Cepat)
CREATE INDEX idx_stock_prices_date ON public.stock_prices(date);
CREATE INDEX idx_predictions_symbol ON public.predictions(symbol);